name: units
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  mfr:
    git: git@github.com:sky-train/mfr.git

dev_dependencies:
  test: ^1.23.1
