name: units
description: A starting point for Dart libraries or applications.
version: 1.0.2
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '^3.0.0'

dev_dependencies:
  test: ^1.25.2
